STUDENTS = [
    {
        "student_id": "SV001",
        "name": "Nguyễn Văn An",
        "age": 25,
        "gender": "Nam",
        "major": "IT",
        "gpa": 3.6,
        "skills": ["Python", "Java"],
    },
    {
        "student_id": "SV002",
        "name": "Trần Thị Hồng",
        "age": 22,
        "gender": "Nữ",
        "major": "Data",
        "gpa": 3.4,
        "skills": ["Python", "SQL"],
    },
    {
        "student_id": "SV003",
        "name": "Phạm Minh Đức",
        "age": 30,
        "gender": "Nam",
        "major": "IT",
        "gpa": 3.8,
        "skills": ["Java", "Spring Boot"],
    },
    {
        "student_id": "SV004",
        "name": "Lê Văn Sơn",
        "age": 27,
        "gender": "Nam",
        "major": "IT",
        "gpa": 2.8,
        "skills": ["C++", "Python"],
    },
    {
        "student_id": "SV005",
        "name": "Hoàng Thu Hoa",
        "age": 24,
        "gender": "Nữ",
        "major": "Data",
        "gpa": 3.9,
        "skills": ["SQL", "Machine Learning"],
    },
]
